# Generated by Django 5.0.4 on 2024-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_rename_register_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellerproductupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('productprice', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='image/')),
                ('productavailsize', models.CharField(max_length=30)),
                ('productdescription', models.CharField(max_length=300)),
            ],
        ),
    ]
