# Generated by Django 5.0.4 on 2024-04-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_sellerproductupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproductupload',
            name='productcategroy',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
