# Generated by Django 5.0.4 on 2024-04-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_sellerproductupload_productcategroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerproductupload',
            old_name='productcategroy',
            new_name='productcategory',
        ),
    ]
