# Generated by Django 5.0.4 on 2024-04-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='selected_size',
            new_name='size_chart',
        ),
    ]
