# Generated by Django 5.0.4 on 2024-05-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_rename_selected_size_wishlist_size_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='size_chart',
        ),
    ]
